<?php
function red_if_zero($value) {
	return sprintf($value > 0 ? '%d' : '<strong>%d</strong>', $value);
}
?>
<!DOCTYPE html>
<html>
	<head>
		<title>Analyse <?=$this->html($kb->title)?></title>
		<link rel="stylesheet" href="webfrontend.css">
		<style>
			h3 {
				border-top: 1px solid black;
				padding: 1em 0;
			}

			h3 small {
				font-weight: normal;

			}

			.hint {
				cursor: help;
				border-bottom: 1px dashed black;
			}

		</style>
	</head>
	<body>
		<nav class="site-nav">
			<ul>
				<li>
					<a class="nav-home" href="index.php"> </a>
				</li>
				<li>
					<a href="webfrontend.php">OPNIEUW</a>
				</li>
				<li>
					<a href="#stats">STATISTIEKEN</a>
				</li>
				<li>
					<a href="#facts">FEITEN</a>
				</li>
				<li>
					<a href="#rules">REGELS</a>
				</li>
				<li>
					<a href="#buildings">GEBOUWEN</a>
				</li>
			</ul>
		</nav>
	<div class="analysis-head">
		<h2>Analysis of <?=$this->html($kb->title)?></h2>
		<p>This is a summary of all the facts, rules, questions in the knowledge base.</p>
	</div>
	<div class="analysis">
			<dl class="stats">
				<h2><a class="anchor" name="stats">Statistics</a></h2>
				<div class="analysis-box">
				<dt>Number of rules: <?=count($kb->rules)?></dt>
				<dt>Number of questions: <?=count($kb->questions)?></dt>
				</div>
			</dl>

			<hr />
			<h2><a class="anchor" name="facts">Facts</a></h2>
			<div class="analysis-box">
			<table class="analysis-table">
				<thead>
					<tr>
						<th>Value</th>
						<th><span class="hint" title="Questions that can cause the fact to become this value">Inferring questions</span></th>
						<th><span class="hint" title="Rules that can cause the fact to become this value">Inferring rules</span></th>
						<th><span class="hint" title="Sum of previous two columns, for determining if this value can be obtained">Inferring questions + rules</span></th>
						<th><span class="hint" title="Rules that test for this value in their condition">Testing rules</span></th>
					</tr>
				</thead>
				<?php foreach ($stats as $fact): ?>
					<tbody>
						<tr class="fact-name">
							<td colspan="5" id="var_<?=$this->id($fact->name)?>">
								<!-- the link causes the system to attempt inferring the specified fact -->
								<a href="webfrontend.php?goals=<?=urlencode($fact->name)?>"><?=$this->html($fact->name)?></a>
							</td>
						</tr>
					<?php foreach ($fact->values as $value => $value_stats): ?>
						<tr>
							<td>
								<?php if (KnowledgeState::is_variable($value)): ?>
								<a href="#var_<?=$this->id(KnowledgeState::variable_name($value))?>"><?=$this->html($value)?></a>
								<?php else: ?>
								<?=$this->html($value)?>
								<?php endif ?>
							</td>
							<td><?=count($value_stats->inferringQuestions)?></td>
							<td><?=count($value_stats->inferringRules)?></td>
							<td><?=red_if_zero(count($value_stats->inferringQuestions) + count($value_stats->inferringRules))?></strong></td>
							<td><?=red_if_zero(count($value_stats->dependingRules))?></td>
						</tr>
					<?php endforeach ?>
					</tbody>
				<?php endforeach ?>
			</table>
			</div>

			<hr />
			<section id="info-rules">
				<h2><a class="anchor" name="rules">Rules</a></h2>
				<?php $formatter = new HTMLFormatter($kb,$checklist); echo $formatter->formatRules()?>
			</section>

			<hr />
			<section id="info-buildings">
				<h2><a class="anchor" name="buildings">Buildings</a></h2>
				<?php echo $formatter->formatBuildings()?>
			</section>
	</div>
	</body>
</html>
