<section>
	<div class="checklist">
		<ol class="checklist_item">
			<form method="post">
			<?php $i = 0; ?>
			<?php foreach ($checklist as $checklist_item): ?>
			<li>
					<label>
						<?=$state->substitute_variables($checklist_item->description, ['Template', 'html'])?>
						<div class="checklist item">
						<p>
						Chance that this will happen:
						</p>
						<div class="checklist option">
							<p>
							<?php echo'<input type="radio" name="radioGroup['.$i.']"
							value="'.ChecklistItem::GREAT.'">'?>
							<p class="textR">Great</p>
							<?php echo'<input type="radio" name="radioGroup['.$i.']"
							value="'.ChecklistItem::SMALL.'">'?>
							<p class="textY">Small</p>
							<?php echo'<input type="radio" name="radioGroup['.$i.']"
							value="'.ChecklistItem::NEGLIGABLE.'" checked="checked" >'?>
							<p class="textG">Negligable</p>
							</p>
						</div>
						<?php $i++; ?>

						<br />
						<p>
						The potential injury of this risk:
						</p>
						<div class="checklist option">
							<p>
							<?php echo'<input type="radio" name="radioGroup['.$i.']"
							value="'.ChecklistItem::GREAT.'">'?>
							<p class="textR">Great</p>
							<?php echo'<input type="radio" name="radioGroup['.$i.']"
							value="'.ChecklistItem::SMALL.'" checked="checked" >'?>
							<p class="textG">Small</p>
							</p>
						</div>
						<?php $i++; ?>
					</label>
				</div>
				<hr />
			</li>
			<?php endforeach ?>
			</form>
		</ol>
		<button type="submit">Continue</button>
	</div>
</section>

