<!DOCTYPE html>
<html>
	<head>
		<title><?=$this->html($state->title) ?></title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="webfrontend">
		<nav class="site-nav">
			<a href="<?=$this->attr($_SERVER['REQUEST_URI'])?>">Start over</a>
			<a href="analyse.php?kb=<?=rawurlencode($_GET['kb'])?>">Analyse</a>
			<a href="index.php">Upload</a>
		</nav>
		<header>
			<h1><?=$this->html($state->title)?></h1>
			<p><?=$state->description?></p>
		</header>
		<div>
			<form method="post">
				<input type="hidden" name="state" value="<?=_encode($state) ?>">
				<input type="hidden" name="log" value="<?=_encode($log) ?>">
				<?=$content?>
			</form>
		</div>

		<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
		<script>
		/* when clicking on an item, select the accompanying radio-button
		and submit the form. Unless the user clicks on a link. */
		$('.question > .options > li')
			.addClass('single-click')
			.click(function(e) {
				if (e.target.nodeName == 'A')
					return;

				var radio = $(this).find('input[type=radio]');
				radio.prop('checked', true);
				e.preventDefault();
				radio.get(0).form.submit();
			});

		$('.question button[type=submit]').hide();
		</script>
	</body>
</html>
