<section class="question">
	<div class="question question_box">
	<p class="pQuestion"><?=$state->substitute_variables($question->description, ['Template', 'html'])?></p>
		<div class="question answer_box">
		<ol class="options">
			<?php foreach ($question->options as $option): ?>
			<li>
				<label>
					<input type="radio" name="answer" value="<?=_encode($option->consequences)?>">
					<?=$state->substitute_variables($option->description, ['Template', 'html'])?>
				</label>
			</li>
			<?php endforeach ?>
		</ol>

		<button type="submit">Continue…</button>
		</div>
	</div>
</section>
