<!DOCTYPE html>
<html>
	<head>
		<title>SafePlace</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body>
		<header>
		</header>
		<div class="single-content">
			<div class="single-box">
			</div>

			<section class="upload-knowledge-base-form">
				<form method="post" enctype="multipart/form-data">
					<div class="single-menu">
						<ul>
							<li>
								<button  class="button run" type="submit" name="action" value="run">START</button>
							</li>
							<li>
								<button class="button analyse" type="submit" name="action" value="analyse">ANALYSE</button>
							</li>
							<li>
								<button  class="button download" type="submit" name="action" value="download">DOWNLOAD</button>
							</li>
								<?php if (current_kb() == MODIFIED_KB): ?>
									<li>
									<button class="button reset" type="submit" name="action" value="reset">RESET</button>
									</li>
								<?php else: ?>
									<li>
									<a class="button upload" href="#chooseFile">UPLOAD</a>
									</li>
									<div id="chooseFile" class="modal">
										<div class="modal-dialog">
    											<div class="modal-content">
      												<div class="head">
        												<a href="#" class="closebtn">x</a>
													     <h2 class="modal-title">Choose file</h2>
      												</div>
  												<div class="container">
													<input type="file" name="knowledgebase" id="input-knowledgebase">

												<button  class="uploadSubmit" type="submit" name="action" value="upload">UPLOAD</button>
												</div>
    											</div>
										</div>
									</div>
								<?php endif ?>
						</ul>
					</div>
				</form>
			</section>
			<?php if ($errors): ?>
			<section class="status-update">
				<p>The following errors occurred:</p>
				<ul>
					<?php foreach ($errors as $error): ?>
					<li>
						<b><?=$this->attr(sprintf('%s, line %d: ',$error->file,$error->line))?></b>
						<?=$this->html($error->message)?>
					</li>
					<?php endforeach ?>
				</ul>
			</section>
			<?php endif ?>

		</div>
		<footer>
			<p>Source code available on <a href="https://github.com/milsen/safeplace">Github</a>.</p>
		</footer>

		<script>
			Array.prototype.forEach.call(
				document.querySelectorAll("a[href^='#']"),
				function(el) {
					console.log(el);
					el.addEventListener('click', function() {
						var hash = el.href.substring(el.href.indexOf('#') + 1);
						var ref = document.getElementById(hash);

						Array.prototype.forEach.call(
							document.querySelectorAll('.highlight'),
							function(node) {
								node.classList.remove('highlight')
							});

						if (ref)
							ref.classList.add('highlight');
					});
				});
		</script>
	</body>
</html>
