<!DOCTYPE html>
<html>
	<head>
		<title>Inference engine</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="kennisbanken">
		<nav class="site-nav">
			<!-- what should come here? -->
		</nav>
		<header>
			<h1>Inference engine</h1>
		</header>

		<?php if ($errors): ?>
		<section class="status-update">
			<p>The following errors occurred:</p>
			<ul>
				<?php foreach ($errors as $error): ?>
				<li>
					<b><?=$this->attr(sprintf('%s, line %d: ',$error->file,$error->line))?></b>
					<?=$this->html($error->message)?>
				</li>
				<?php endforeach ?>
			</ul>
		</section>
		<?php endif ?>

		<section class="upload-knowledge-base-form">
			<?php if (current_kb() == DEFAULT_KB): ?>
				<h1>Currently using the default database.</h1>
			<?php elseif (current_kb() == MODIFIED_KB): ?>
				<h1>Currently using a non-default database, last modified <?=date("d-m-Y, H:i:s.", filemtime(MODIFIED_KB))?></h1>
			<?php else: ?>
				<h1>A knowledge base error occurred. Please contact the system administrator.</h1>
			<?php endif ?>
			<form method="post" enctype="multipart/form-data">
				<div class="controls">
					<button type="submit" name="action" value="run">Run</button>
					<button type="submit" name="action" value="analyse">Analyse</button>
					<button type="submit" name="action" value="download">Download</button>
				</div>
				<div>
					<label for="input-knowledgebase">Knowledge base XML file:</label>
					<input type="file" name="knowledgebase" id="input-knowledgebase">
				</div>
				<div class="controls">
					<button type="submit" name="action" value="upload">Upload</button>
					<button type="submit" name="action" value="reset">Reset to Default</button>
				</div>
			</form>
		</section>

		<footer>
			<p>Source code available on <a href="https://github.com/jelmervdl/kennissysteem">Github</a>.</p>
		</footer>

		<script>
			Array.prototype.forEach.call(
				document.querySelectorAll("a[href^='#']"),
				function(el) {
					console.log(el);
					el.addEventListener('click', function() {
						var hash = el.href.substring(el.href.indexOf('#') + 1);
						var ref = document.getElementById(hash);

						Array.prototype.forEach.call(
							document.querySelectorAll('.highlight'),
							function(node) {
								node.classList.remove('highlight')
							});

						if (ref)
							ref.classList.add('highlight');
					});
				});
		</script>
	</body>
</html>
